"""create subcategory

Revision ID: 66a2abd6dc3a
Revises: 2db213272c6c
Create Date: 2024-09-16 14:21:08.852090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a2abd6dc3a'
down_revision: Union[str, None] = '2db213272c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_category_id'), 'sub_category', ['id'], unique=True)
    op.create_index(op.f('ix_sub_category_sort_order'), 'sub_category', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_category_sort_order'), table_name='sub_category')
    op.drop_index(op.f('ix_sub_category_id'), table_name='sub_category')
    op.drop_table('sub_category')
    # ### end Alembic commands ###
