"""set unique true for all table name fields

Revision ID: a01a6f4a3850
Revises: 61b9eae1735d
Create Date: 2024-09-18 14:19:57.353943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01a6f4a3850'
down_revision: Union[str, None] = '61b9eae1735d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['name'])
    op.create_unique_constraint(None, 'option', ['name'])
    op.create_unique_constraint(None, 'product', ['name'])
    op.create_unique_constraint(None, 'sub_category', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_category', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'option', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
